/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-04 22:13:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Ottawa's Best Rated Restaurants</title>\r\n");
      out.write("\t\t<!-- <meta charset=\"utf-8\"> -->\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ionicons/css/ionicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ospoon.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg main-navbar\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\t\t\t\r\n");
      out.write("<!--\t\t\t  <a class=\"navbar-brand\" href=\"#\"></a>-->\r\n");
      out.write("\t\t\t  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t    <span class=\"navbar-toggler-icon\">\r\n");
      out.write("\t\t\t    \t<i class=\"ion-navicon\"></i>\r\n");
      out.write("\t\t\t    </span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("\t\t\t\t  <div class=\"mr-auto\"></div>\r\n");
      out.write("\t\t\t    <ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t    \t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t        <a class=\"nav-link smooth-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/query\">Advanced Queries</a>\r\n");
      out.write("\t\t\t      </li>\r\n");
      out.write("\t\t\t      <li class=\"nav-item\">\r\n");
      out.write("\t\t\t        <a class=\"nav-link smooth-link\" href=\"#mostpopular\">Most Popular</a>\r\n");
      out.write("\t\t\t      </li>\r\n");
      out.write("\t\t\t      <li class=\"nav-item\">\r\n");
      out.write("\t\t\t        <a class=\"nav-link smooth-link\" href=\"#categories\">Categories</a>\r\n");
      out.write("\t\t\t      </li>\r\n");
      out.write("\t\t\t      <li class=\"nav-item\">\r\n");
      out.write("\t\t\t        <a class=\"nav-link smooth-link\" href=\"#categories\">Restaurants</a>\r\n");
      out.write("\t\t\t      </li>\r\n");
      out.write("\t\t\t    </ul>'\r\n");
      out.write("\t\t\t    <form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"btn smooth-link align-middle btn-primary\">Login</a>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section class=\"hero bg-overlay\" id=\"hero\" data-bg=\"img/hero.jpeg\">\r\n");
      out.write("\t\t\t<div class=\"text py-5\">\r\n");
      out.write("\t\t\t\t<img src=\"img/logo-black-spoon.png\" alt=\"Logo\" id=\"logo\">\r\n");
      out.write("\t\t\t\t<h1>Ottawa<span class=\"bold\">Spoon</span></h1>\r\n");
      out.write("\t\t\t\t<p>Ottawa's Best Rated Restaurants.</p>\r\n");
      out.write("\t\t\t\t<div class=\"cta\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"search\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"restaurantName\" class=\"form-control\" placeholder=\"Restaurant name\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-primary\">Find</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"link\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">List of All Restaurants</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("<!--\t\t\t\t<figure><img src=\"img/logo-black-spoon.png\" alt=\"Logo\"></figure>-->\r\n");
      out.write("\t\t\t\t<!-- <p>Copyright &copy; 2018 OttawaSpoon</p> -->\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tA Project By <a href=\"javascript:\" onclick=\"changeLogo('img/logo-animate-fast.gif');\">Parami</a>, \r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:\" onclick=\"changeLogo('img/logo-artem.png');\">Artem</a> &amp; \r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:\" onclick=\"changeLogo('img/logo-alex.png');\">Alex</a>.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- TODO: Make this a toggle -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction changeLogo(image){\r\n");
      out.write("\t\t\t\tvar logoHolder = document.getElementById(\"logo\");\r\n");
      out.write("\t\t\t\t// console.log(logoHolder.src);\r\n");
      out.write("\t\t\t\t// console.log(logoHolder.image);\r\n");
      out.write("\t\t\t\t// if (logoHolder.src != image) {\r\n");
      out.write("\t\t\t\t\tlogoHolder.src = \"img/logo-black-spoon.png\";\r\n");
      out.write("\t\t\t\t// } else {\r\n");
      out.write("\t\t\t\t\tlogoHolder.src = image;\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.easeScroll.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/ospoon.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
